apiVersion: batch/v1
kind: CronJob
metadata:
 name: cronjob-demo
spec:
 schedule: "*/2 * * * *"   # Every 2 minutes
 jobTemplate:
   spec:
     template:
       spec:
         containers:
         - name: hello
           image: busybox
           command: ['sh', '-c', 'echo "Hello from $(date)"']
         restartPolicy: OnFailure

