apiVersion: batch/v1
kind: Job
metadata:
 name: job-demo
spec:
 template:
   spec:
     containers:
     - name: worker
       image: busybox
       command: ['sh', '-c', 'echo "Processing..."; sleep 5; echo "Done"']
     restartPolicy: Never