apiVersion: batch/v1
kind: Job
metadata:
 name: parallel-job
 namespace: demo
spec:
 completions: 4
 parallelism: 2
 template:
   spec:
     containers:
     - name: worker
       image: busybox
       command: ['sh', '-c', 'echo "Task $(hostname)"; sleep 30']
     restartPolicy: Never