apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-rs
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
        - name: hello
          image: nginx:1.27
          ports:
            - containerPort: 80