# ---------- Build stage ----------
FROM python:latest

WORKDIR /build

COPY requirements.txt .
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# ---------- Runtime stage ----------
FROM gcr.io/distroless/static-debian13

WORKDIR /app

COPY --from=builder /install /usr/local
COPY app.py .

EXPOSE 8080

USER 1000

CMD ["python", "app.py"]