name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t hello-app:${{ github.sha }} .

      - name: Run basic security check
        run: |
          docker run --rm hello-app:${{ github.sha }} python --version

      - name: Image digest (immutability proof)
        run: |
          docker inspect hello-app:${{ github.sha }} --format='{{.Id}}'